version: '3.1'
services:
  postgres:
    image: postgres:14.5-alpine
    restart: always
    command: postgres -c 'max_connections=500' 
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./storage/db:/var/lib/postgresql/data
